package com.shadov.codehellven.api.task.domain.exception

internal class TaskUpdateException : RuntimeException("Exception occured during task update")